version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "123456"
    ports:
      - "15432:5432"
    # volumes:
    #   - /home/xxx/<path>:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
      
  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "defaultPassword"
    ports:
      - "8081:80"
    depends_on:
      - teste-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
