spring:
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    hibernate:
      'ddl-auto': none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    banner-mode: off

logging:
  level:
    org:
      springframework: ERROR
